service: vhub

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: python3.7
  region: us-east-2

package:
  exclude:
    - node_modules/**
    - tests/**

functions:
  fetch_video:
    handler: vhub.fetch_video.lambda_handler
    events:
      - s3: crawled-webpages
    environment:
      GOOGLE_CLOUD_API_KEY: ${ssm:Google_Cloud_API_key~true}
    timeout: 900
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource:
          - Fn::GetAtt:
            - VideosTable
            - Arn
      - Effect: Allow
        Action:
          - s3:ListBucket
        Resource:
          - arn:aws:s3:::crawled-webpages
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource:
          - arn:aws:s3:::crawled-webpages/*
  fetch_channel:
    handler: vhub.fetch_channel.lambda_handler
    events:
      - s3: crawled-channels
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource:
          Fn::GetAtt:
            - ChannelsTable
            - Arn
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource:
          - arn:aws:s3:::crawled-channels/*
  notifier:
    handler: vhub.notifier.lambda_handler
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          arn:
            Fn::GetAtt:
              - VideosTable
              - StreamArn
    environment:
      TWITTER_CONSUMER_KEY: ${ssm:Twitter_Consumer_Key~true}
      TWITTER_CONSUMER_SECRET: ${ssm:Twitter_Consumer_Secret~true}
      TWITTER_ACCESS_TOKEN: ${ssm:Twitter_Access_Token~true}
      TWITTER_ACCESS_SECRET: ${ssm:Twitter_Access_Secret~true}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource:
          - Fn::GetAtt:
            - ChannelsTable
            - Arn

resources:
  Resources:
    VideosTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Videos
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: url
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    ChannelsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Channels
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: url
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 20
