service: vhub

plugins:
  - serverless-iam-roles-per-function
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: python3.7
  region: us-east-2

package:
  exclude:
    - node_modules/**
    - tests/**
    - venv/**
    - .pytest_cache/**
    - .vscode/**

functions:
  fetch_vtuber_antenna:
    handler: vhub.fetch_vtuber_antenna.lambda_handler
    events:
      - schedule: rate(5 minutes)
    timeout: 10
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource:
          - arn:aws:s3:::crawled-webpages-vtuber-antenna/*
  fetch_video:
    handler: vhub.fetch_video.lambda_handler
    events:
      - s3: crawled-webpages-vtuber-antenna
    timeout: 900
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource:
          - Fn::GetAtt:
            - VideosTable
            - Arn
      - Effect: Allow
        Action:
          - s3:ListBucket
        Resource:
          - arn:aws:s3:::crawled-webpages-vtuber-antenna
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource:
          - arn:aws:s3:::crawled-webpages-vtuber-antenna/*
  notifier:
    handler: vhub.notifier.lambda_handler
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          arn:
            Fn::GetAtt:
              - VideosTable
              - StreamArn
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource:
          - Fn::GetAtt:
            - ChannelsTable
            - Arn

resources:
  Resources:
    VideosTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Videos
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: url
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    ChannelsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Channels
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: url
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 20
